export const users = [
    {
        id: 1,
        image: "https://randomuser.me/api/portraits/women/88.jpg",
        date: "Jan 12, 2022",
        name: 'Alice Freeman',
        isOnline: true,
        message: "You are the worst",
    },
    {
        id: 2,
        image: "https://randomuser.me/api/portraits/women/48.jpg",
        date: "Feb 18, 2022",
        name: "Josephina",
        isOnline: true,
        message: "We are losing money! Quick!",
    },
    {
        id: 3,
        image: "https://randomuser.me/api/portraits/men/6.jpg",
        date: "Feb 18, 2022",
        name: 'Velazquez',
        isOnline: true,
        message: "Quickly come to the meeting room 1B, we have a big server issue",
    },
    {
        id: 4,
        image: "https://randomuser.me/api/portraits/women/49.jpg",
        date: "Feb 14, 2022",
        name: 'Barrera',
        isOnline: false,
        message: 'We need you!',
    },
    {
        id: 5,
        image: "https://randomuser.me/api/portraits/men/28.jpg",
        date: "Feb 18, 2022",
        name: 'Louis',
        isOnline: true,
        message: 'Hurry up! Everyone is waiting for you!',
    },
    {
        id: 6,
        image: "https://randomuser.me/api/portraits/women/90.jpg",
        date: "March 22, 2022",
        name: 'Paulina',
        isOnline: false,
        message: 'Ok, i will try to do it.',
    },
    {
        id: 7,
        image: "https://randomuser.me/api/portraits/men/44.jpg",
        date: "April 26, 2022",
        name: 'Mark',
        isOnline: true,
        message: "Okay, have a nice day!",
    },
    {
        id: 8,
        image: "https://randomuser.me/api/portraits/men/61.jpg",
        date: "Feb 18, 2022",
        name: 'Carl',
        isOnline: false,
        message: "You have 5 min! I cover you!",
    },
    {
        id: 9,
        image: "https://randomuser.me/api/portraits/women/77.jpg",
        date: "May 7, 2022",
        name: 'Kate',
        isOnline: true,
        message: "See you later!",
    },
    {
        id: 10,
        image: "https://randomuser.me/api/portraits/women/29.jpg",
        date: "June 29, 2022",
        name: 'Sophie',
        isOnline: true,
        message: "You need to upload your code",
    },

]